"""Institutional regimen catalog snapshot from regimenes.xlsx (deduplicated)."""

REGIMEN_CATALOG_2026: tuple[tuple[int, str], ...] = (
    (2, "Liviano c/ Fruta Cruda"),
    (3, "Liviano (familiar)"),
    (4, "Liviano"),
    (5, "Liviano s/pan"),
    (6, "Liviano s/s+1"),
    (7, "Liviano s/s+2"),
    (8, "Liviano s/az"),
    (9, "Liviano s/az s/s+1"),
    (10, "Liviano s/az s/pan"),
    (11, "Bldo s/residuos"),
    (12, "Bldo s/residuos s/s"),
    (13, "Bldo s/residuos s/s+1"),
    (14, "Bldo s/r s/s+2"),
    (15, "Bldo s/r s/az"),
    (16, "Bldo s/r s/az s/s+1"),
    (17, "Bldo s/r s/az s/s+2"),
    (18, "INDICADO"),
    (19, "INDICADO s/s"),
    (20, "INDICADO s/s+1"),
    (21, "INDICADO s/s+2"),
    (22, "INDICADO s/r"),
    (23, "INDICADO s/res s/s+1"),
    (24, "INDICADO s/r s/s+2"),
    (25, "Papilla NO suple"),
    (26, "Papilla s/s"),
    (27, "Papilla s/s+1"),
    (28, "Papilla s/s+2"),
    (29, "Papilla s/az"),
    (30, "Papilla s/az s/s+1"),
    (31, "Papilla s/az s/s+2"),
    (32, "Papilla s/residuos"),
    (33, "Papilla s/residuo s/s"),
    (34, "Papilla s/residuo s/s+1"),
    (35, "Papilla s/residuo s/s+2"),
    (36, "Papilla s/residuos s/az"),
    (37, "Papilla s/residuo s/az s/s+1"),
    (38, "Papilla s/residuo s/az s/s+2"),
    (39, "Papilla x cedazo"),
    (40, "Papilla x cedazo s/s"),
    (41, "Papilla x cedazo s/s+1"),
    (42, "Papilla x cedazo s/s+2"),
    (43, "Papilla x cedazo s/az"),
    (44, "Papilla x cedazo s/az s/s+1"),
    (45, "Papilla chancada"),
    (46, "Papilla chancada s/s"),
    (47, "Papilla chancada s/s+1"),
    (48, "Papilla chancada s/s+2"),
    (49, "Papilla chancada s/az"),
    (50, "Papilla chancada s/az s/s+1"),
    (51, "Papilla chancada s/az s/s+2"),
    (52, "Líquido"),
    (53, "Líquido s/s"),
    (54, "Líquido s/s+1"),
    (55, "Líquido s/s+2"),
    (56, "Líquido s/az"),
    (57, "Líquido s/az s/s+1"),
    (58, "Líquido s/az s/s+2"),
    (59, "Sopa Mixta"),
    (60, "Hídrico"),
    (61, "Líquido x cedazo"),
    (62, "NE"),
    (63, "Nutricion Parenteral Central"),
    (64, "Nutricion Parenteral Periferica"),
    (65, "Regimen 0"),
    (66, "Ayunas"),
    (67, "Liviano + Acompañante"),
    (68, "Papilla Terapéutica NO suple"),
    (69, "Colacion"),
    (70, "Colacion diet"),
    (71, "Colacion papilla"),
    (72, "Colacion papilla diet"),
    (73, "Compota"),
    (74, "Compota licuada"),
    (75, "Colacion x cedazo"),
    (76, "Compota x cedazo"),
    (77, "Yogurt"),
    (78, "Yogurt diet"),
    (79, "Yogurt sin lactosa"),
    (80, "Jalea"),
    (81, "Jalea diet"),
    (82, "Diben drink"),
    (83, "Ensure Clinical"),
    (84, "Fruta Chica"),
    (85, "Fresubin Postre"),
    (86, "Ensure Advance"),
    (87, "Glucerna Drink"),
    (88, "Té"),
    (89, "Té solo"),
    (90, "Agua de hierba"),
    (91, "Agua de hierba sola"),
    (92, "Leche"),
    (93, "Leche sola"),
    (94, "Chuño"),
    (95, "Chuño solo"),
    (96, "Leche con 1 medida de espesante"),
    (97, "Leche con 2 medida de espesante"),
    (98, "Leche con 3 medida de espesante"),
    (99, "Leche sola con 1 medida de espesante"),
    (100, "Leche sola con 2 medida de espesante"),
    (101, "Leche sola con 3 medida de espesante"),
    (102, "Leche con té"),
    (103, "Leche sola con té"),
    (104, "Leche con chuño"),
    (105, "Leche con chuño con 1 medida de modulo calorico"),
    (106, "Leche con chuño con 2 medida de modulo calorico"),
    (107, "Leche con chuño con 3 medida de modulo calorico"),
    (108, "Leche con chuño con 1 medida de modulo proteico"),
    (109, "Leche con chuño con 2 medida de modulo proteico"),
    (110, "Leche con chuño con 3 medida de modulo proteico"),
    (111, "Leche sin lactosa"),
    (112, "Leche sin lactosa con té"),
    (113, "Leche sin lactosa con chuño"),
    (114, "Leche sin lactosa con chuño con 1 medida de modulo calorico"),
    (115, "Leche sin lactosa con chuño con 2 medida de modulo calorico"),
    (116, "Leche sin lactosa con chuño con 3 medida de modulo calorico"),
    (117, "Leche sin lactosa con chuño con 1 medida de modulo proteico"),
    (118, "Leche sin lactosa con chuño con 2 medida de modulo proteico"),
    (119, "Leche sin lactosa con chuño con 3 medida de modulo proteico"),
    (120, "Chuño con 1 medida de espesante"),
    (121, "Chuño con 2 medida de espesante"),
    (122, "Chuño con 3 medida de espesante"),
    (123, "Chuño con 1 medida de modulo calorico"),
    (124, "Chuño con 2 medida de modulo calorico"),
    (125, "Chuño con 3 medida de modulo calorico"),
    (126, "Chuño con 1 medida de modulo proteico"),
    (127, "Chuño con 2 medida de modulo proteico"),
    (128, "Chuño con 3 medida de modulo proteico"),
    (129, "Supportan"),
    (131, "Té con pan de molde agregado"),
    (132, "Té con pan de molde agregado (no mermelada)"),
    (133, "Té con pan de molde agregado (no quesillo)"),
    (134, "Té con pan de molde agregado (quesillo)"),
    (135, "Té con pan de molde agregado (merme)"),
    (136, "Té con pan de molde integral agregado"),
    (137, "Té con pan de molde integral agregado (no mermelada)"),
    (138, "Té con pan de molde integral agregado (no quesillo)"),
    (139, "Té con pan de molde integral agregado (quesillo)"),
    (140, "Té con pan de molde integral agregado (merme)"),
    (141, "Té con galletas agregado"),
    (142, "Té con galletas agregado (no mermelada)"),
    (143, "Té con galletas agregado (no quesillo)"),
    (144, "Té con galletas agregado (quesillo)"),
    (145, "Té con galletas agregado (merme)"),
)
